"""Anomaly-detection benchmark over air-quality series (genias-style, our data).

A stripped, renamed fork of the genias benchmark library: detector models, the
VUS/affiliation metric set, and the benchmark plots, wired into an end-to-end
benchmark (load → preprocess → inject STL-combined anomalies → detect → ensemble
→ metrics → results.json). Plots are generated by the separate
:mod:`airquality.anomaly.plot_benchmark_results` script. The ``GenIAS`` VAE keeps
its name (it backs the ``*GenIAS`` detector variants).
"""

from __future__ import annotations

from .benchmark import (
    AnomalyBenchmarkConfig,
    AnomalyCase,
    build_cases,
    run_benchmark,
)
from .ensemble import DEFAULT_ENSEMBLE_METHOD, ENSEMBLE_METHODS, consensus, rank_top_k
from .metrics import compute_metrics
from .registry import MODEL_REGISTRY, resolve_model_names

__all__ = [
    "AnomalyCase",
    "AnomalyBenchmarkConfig",
    "DEFAULT_ENSEMBLE_METHOD",
    "ENSEMBLE_METHODS",
    "MODEL_REGISTRY",
    "build_cases",
    "compute_metrics",
    "consensus",
    "rank_top_k",
    "resolve_model_names",
    "run_benchmark",
]
