"""Anomaly-detection benchmark over air-quality series, with two modes.

A stripped, renamed fork of the genias benchmark library: detector models and
the benchmark plots, wired into an end-to-end benchmark (load → preprocess →
detect → ensemble → results.json) with two evaluation modes:

- ``unlabeled`` (default, matches production): no ground truth — scores are
  binarized with a median + k·MAD threshold and detectors whose detection rate
  exceeds ``max_detection_rate`` (default 7%) are discarded; survivors form the
  consensus ensemble.
- ``synthetic``: anomalies (:data:`~airquality.anomaly.benchmark.INJECTION_VARIANT`,
  ``combined`` shapes) are injected directly into the real series — no STL
  synthetic base — and detectors are scored with the supervised metric set
  (VUS-PR et al.); the ensemble is the top-k by selection-injection VUS-PR.

Plots are generated by the separate
:mod:`airquality.anomaly.plot_benchmark_results` script. The ``GenIAS`` VAE
keeps its name (it backs the ``*GenIAS`` detector variants, which synthesize
anomalous *training* windows internally).
"""

from __future__ import annotations

from .benchmark import (
    INJECTION_VARIANT,
    MODES,
    AnomalyBenchmarkConfig,
    AnomalyCase,
    build_cases,
    run_benchmark,
    split_by_detection_rate,
)
from .ensemble import DEFAULT_ENSEMBLE_METHOD, ENSEMBLE_METHODS, consensus, rank_top_k
from .metrics import (
    DEFAULT_MAX_DETECTION_RATE,
    DEFAULT_THRESHOLD_K,
    compute_metrics,
    detect_mask,
    detection_rate,
    mad_threshold,
    vus_sliding_window,
)
from .registry import MODEL_REGISTRY, resolve_model_names

__all__ = [
    "AnomalyCase",
    "AnomalyBenchmarkConfig",
    "DEFAULT_ENSEMBLE_METHOD",
    "DEFAULT_MAX_DETECTION_RATE",
    "DEFAULT_THRESHOLD_K",
    "ENSEMBLE_METHODS",
    "INJECTION_VARIANT",
    "MODEL_REGISTRY",
    "MODES",
    "build_cases",
    "compute_metrics",
    "consensus",
    "detect_mask",
    "detection_rate",
    "mad_threshold",
    "rank_top_k",
    "resolve_model_names",
    "run_benchmark",
    "split_by_detection_rate",
    "vus_sliding_window",
]
