"""Label-free anomaly-detection benchmark over air-quality series.

A stripped, renamed fork of the genias benchmark library: detector models and
the benchmark plots, wired into an end-to-end benchmark (load → preprocess →
detect on the real series → MAD-threshold scores → detection-rate filter →
ensemble of survivors → results.json). There are no anomaly labels — detectors
are screened by their detection rate (sensor faults are rare, so flagging more
than ``max_detection_rate`` means flagging normal variation). Plots are
generated by the separate :mod:`airquality.anomaly.plot_benchmark_results`
script. The ``GenIAS`` VAE keeps its name (it backs the ``*GenIAS`` detector
variants, which synthesize anomalous *training* windows internally).
"""

from __future__ import annotations

from .benchmark import (
    AnomalyBenchmarkConfig,
    AnomalyCase,
    build_cases,
    run_benchmark,
    split_by_detection_rate,
)
from .ensemble import DEFAULT_ENSEMBLE_METHOD, ENSEMBLE_METHODS, consensus
from .metrics import (
    DEFAULT_MAX_DETECTION_RATE,
    DEFAULT_THRESHOLD_K,
    detect_mask,
    detection_rate,
    mad_threshold,
)
from .registry import MODEL_REGISTRY, resolve_model_names

__all__ = [
    "AnomalyCase",
    "AnomalyBenchmarkConfig",
    "DEFAULT_ENSEMBLE_METHOD",
    "DEFAULT_MAX_DETECTION_RATE",
    "DEFAULT_THRESHOLD_K",
    "ENSEMBLE_METHODS",
    "MODEL_REGISTRY",
    "build_cases",
    "consensus",
    "detect_mask",
    "detection_rate",
    "mad_threshold",
    "resolve_model_names",
    "run_benchmark",
    "split_by_detection_rate",
]
